image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - integration_test

integration_test_server:
  stage: integration_test
  tags: [unittest]
  before_script:
    - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
    - curl -L https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  script:
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle --build-cache assemble
    - gradle integrationTest --info
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml
