image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - integration_test

build_server:
  stage: build
  tags: [unittest]
  before_script:
  - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
  script: 
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - chatup_server/build
      - chatup_server/.gradle

integration_test_server:
  stage: integration_test
  tags: [unittest]
  before_script:
    - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
    - ls /var/run | grep docker
  script:
    - echo "BUILDING"
    - ls /builds/pap-22z/pap22z-z02/chatup_server/src/integrationTest/resources
    - cd "$CI_PROJECT_DIR/chatup_server"
    - echo pwd
    - ls -al /src/integrationTest/resources
    - gradle integrationTest --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - chatup_server/build
      - chatup_server/.gradle
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml