image: amidos/dcind:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - integration_test

integration_test_server:
  stage: integration_test
  tags: [unittest]
  before_script:
    - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
  script:
    - cd "$CI_PROJECT_DIR/chatup_server"
    - ./gradlew --build-cache assemble
    - ./gradlew integrationTest --info
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml
