image: gradle:alpine

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - integration_test

integration_test_server:
  stage: integration_test
  tags: [unittest]
  before_script:
    - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
  script:
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle --build-cache assemble
    - gradle integrationTest --info
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml
