image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - integration_test

build_server:
  stage: build
  tags: [unittest]
  before_script:
  - GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
  - export GRADLE_USER_HOME
  script: 
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - chatup_server/build
      - chatup_server/.gradle

test_server:
  services:
  - postgres
  variables:
    POSTGRES_DB: chat
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: test
  tags: [unittest]
  before_script:
  - GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
  - export GRADLE_USER_HOME
  script:
    - cd "$CI_PROJECT_DIR/chatup_server" 
    - gradle check --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - chatup_server/build
      - chatup_server/.gradle
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/test/**/TEST-*xml
    reports:
      junit: chatup_server/build/test-results/test/**/TEST-*.xml

integration_test_server:
#  variables:
#    TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  stage: integration_test
  tags: [unittest]
  before_script:
    - GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
    - export GRADLE_USER_HOME
    - ls /var/run | grep docker
  script:
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle integrationTest --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - chatup_server/build
      - chatup_server/.gradle
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml

build_client:
  stage: build
  tags: [unittest]
  before_script:
  - GRADLE_USER_HOME="$(pwd)/chatup_client/.gradle"
  - export GRADLE_USER_HOME
  - apt-get install -y libx11-6
  script: 
    - cd "$CI_PROJECT_DIR/chatup_client"
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - chatup_client/build
      - chatup_client/.gradle

test_client:
  stage: test
  tags: [unittest]
  before_script:
  - GRADLE_USER_HOME="$(pwd)/chatup_client/.gradle"
  - export GRADLE_USER_HOME
  - apt-get install -y libx11-6
  script:
    - cd "$CI_PROJECT_DIR/chatup_client" 
    - gradle check --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - chatup_client/build
      - chatup_client/.gradle
  artifacts:
    when: always
    paths:
      - chatup_client/build/test-results/test/**/TEST-*.xml
    reports:
      junit: chatup_client/build/test-results/test/**/TEST-*.xml