image: gradle:alpine

stages:
  - integration_test

integration_test_server:
  # image: gradle:alpine
  stage: integration_test
  tags: [unittest]
  variables:
    # TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
    TESTCONTAINERS_RYUK_DISABLED: "true"
  before_script:
    - export GRADLE_USER_HOME="$(pwd)/chatup_server/.gradle"
    - apk update
    - apk add --update docker docker-compose openrc iptables ip6tables
    # - iptables -A INPUT -i docker0 -j ACCEPT
    # - rc-update add docker boot
  script:
    - cd "$CI_PROJECT_DIR/chatup_server"
    - gradle --build-cache assemble
    - gradle integrationTest --info
  artifacts:
    when: always
    paths:
      - chatup_server/build/test-results/integrationTest/**/TEST-*.xml
    reports:
      junit: chatup_server/build/test-results/integrationTest/**/TEST-*.xml
