version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: java -jar build/libs/chatup_server-0.0.1-SNAPSHOT.jar
