spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

app:
  jwt:
    secretKey: cdrNaN7Ksz33GNDuNzWqLP0d
    tokenPrefix: Bearer
    daysExpire: 999999
  feed:
    pageSize: 10

