spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/chat
    username: postgres
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        search:
          backend:
            hosts: elasticsearch:9200
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  rabbitmq:
    host: rabbitmq
    relay-port: 61613
    relay-host: rabbitmq


app:
  jwt:
    secretKey: cdrNaN7Ksz33GNDuNzWqLP0d
    tokenPrefix: Bearer
    daysExpire: 999999
  feed:
    pageSize: 10

